name: "Build Docker Images For Testing"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    # build with docker so we can use layer caching
    name: Build Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-image: [django, nginx]
        os: [debian]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Read Docker Image Identifiers
        id: read-docker-image-identifiers
        run: echo "IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          driver-opts: image=moby/buildkit:master # needed to get the fix for https://github.com/moby/buildkit/issues/2426
          
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v6
        timeout-minutes: 10
        with:
          context: .
          push: false
          tags: defectdojo/defectdojo-${{ matrix.docker-image }}:${{ matrix.os }}
          file: Dockerfile.${{ matrix.docker-image }}-${{ matrix.os }}
          outputs: type=docker,dest=${{ matrix.docker-image }}-${{ matrix.os }}_img
          cache-from: type=gha,scope=${{ matrix.docker-image }}
          cache-to: type=gha,mode=max,scope=${{ matrix.docker-image }}

      - name: list current files
        run: |
          ls -la
          docker image ls 
        
      - name: Load docker images
        timeout-minutes: 10
        run: |-
             docker load -i ${{ matrix.docker-image }}-${{ matrix.os }}_img
             docker images
      
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
            image-ref: ${{ matrix.docker-image }}-${{ matrix.os }}_img
            
      # export docker images to be used in next jobs below
      - name: Upload image ${{ matrix.docker-image }} as artifact
        timeout-minutes: 10
        uses:  actions/upload-artifact@v3
        with:
          name: ${{ matrix.docker-image }}
          path: ${{ matrix.docker-image }}-${{ matrix.os }}_img
          retention-days: 1
